/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c7c6c6",
        "on-secondary": "#2f3131",
        "secondary": "#c7c6c6",
        "on-background": "#e0e2ed",
        "surface": "#10131b",
        "background": "#10131b",
        "on-primary-container": "#00285d",
        "on-surface-variant": "#c1c6d7",
        "on-secondary-fixed-variant": "#464747",
        "surface-variant": "#31353d",
        "outline": "#8b90a0",
        "surface-container-highest": "#31353d",
        "error": "#ffb4ab",
        "inverse-surface": "#e0e2ed",
        "primary-container": "#4d8eff",
        "on-tertiary-fixed": "#360f00",
        "inverse-primary": "#005ac3",
        "surface-container": "#1c2028",
        "on-tertiary": "#581e00",
        "primary": "#aec6ff",
        "primary-fixed-dim": "#aec6ff",
        "surface-tint": "#aec6ff",
        "surface-container-high": "#272a32",
        "tertiary-fixed-dim": "#ffb596",
        "on-primary": "#002e6a",
        "outline-variant": "#414755",
        "on-primary-fixed-variant": "#004395",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-primary-fixed": "#001a42",
        "tertiary-fixed": "#ffdbcd",
        "inverse-on-surface": "#2d3039",
        "surface-container-low": "#181b23",
        "secondary-fixed": "#e3e2e2",
        "on-surface": "#e0e2ed",
        "surface-bright": "#363942",
        "tertiary-container": "#f0661c",
        "error-container": "#93000a",
        "surface-dim": "#10131b",
        "surface-container-lowest": "#0b0e16",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#1a1c1c",
        "secondary-container": "#484949",
        "tertiary": "#ffb596",
        "on-tertiary-container": "#4d1900",
        "on-error": "#690005",
        "primary-fixed": "#d8e2ff",
        "on-secondary-container": "#b8b8b8"
      },
      spacing: {
        "sm": "12px",
        "margin-mobile": "16px",
        "xl": "32px",
        "margin-desktop": "40px",
        "base": "4px",
        "md": "16px",
        "gutter": "16px",
        "xs": "8px",
        "lg": "24px"
      },
    },
  },
  plugins: [],
}